name: Build aarch64 Tauri App

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-linux-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            pkg-config \
            libgtk-3-dev \
            libglib2.0-dev \
            libwebkit2gtk-4.0-dev \
            libsoup2.4-dev \
            libpango1.0-dev \
            libatk1.0-dev \
            libcairo2-dev \
            xz-utils

      - name: Install Rust with aarch64 target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install project dependencies
        run: |
          npm install
          npm install -g @tauri-apps/cli

      - name: Set environment variables for pkg-config
        run: |
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Build Tauri app for aarch64
        run: |
          npm run tauri build -- --target aarch64-unknown-linux-gnu

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-aarch64-bundle
          path: src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/
