name: Build aarch64 binary with cross

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y pkg-config curl wget xz-utils libgtk-3-dev libglib2.0-dev

      - name: Install Rust + cross
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend deps
        run: |
          npm install
          npm install -g @tauri-apps/cli

      - name: Install cross
        run: cargo install cross

      - name: Build binary with cross
        run: cross build --target aarch64-unknown-linux-gnu --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-aarch64-bin
          path: src-tauri/target/aarch64-unknown-linux-gnu/release/yourapp
