name: Build Tauri aarch64

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-aarch64:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev:arm64 \
            libgtk-3-dev:arm64 \
            libpango1.0-dev:arm64 \
            libsoup2.4-dev:arm64 \
            libatk1.0-dev:arm64 \
            libcairo2-dev:arm64 \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            pkg-config \
            curl \
            wget

      - name: Install Rust and target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-unknown-linux-gnu

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install
          npm install -g @tauri-apps/cli

      - name: Set up environment for pkg-config
        run: |
          echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV
          echo "PKG_CONFIG_LIBDIR=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Build Tauri (aarch64)
        run: |
          npm run tauri build -- --target aarch64-unknown-linux-gnu

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tauri-aarch64-artifacts
          path: |
            src-tauri/target/aarch64-unknown-linux-gnu/release/bundle
